#!/bin/bash

echo "Menambahkan semua file..."
git add *

echo "Membuat commit..."
read -p "Masukkan pesan commit: " commit_message
git commit -m "$commit_message"

echo "Mengecek status branch..."
status=$(git status)
if [[ $status == "nothing to commit, working tree clean" ]]; then
echo "Tidak ada perubahan baru, keluar dari script."
exit 0
fi

echo "Menyimpan perubahan ke repository remote..."
git push -u origin HEAD
if [[ $? -eq 0 ]]; then
echo "Perubahan berhasil diterbitkan ke repository remote."
else
if [[ $status == "Your branch is ahead of 'origin/main' by 1 commit" ]]; then
echo "Branch local sudah terdepan 1 commit. Melakukan push force..."
git push -f origin HEAD
if [[ $? -eq 0 ]]; then
echo "Perubahan berhasil diterbitkan ke repository remote."
else
echo "Error: Terjadi kesalahan saat menerbitkan perubahan."
fi
else
echo "Error: Terjadi kesalahan saat menerbitkan perubahan."
fi
fi

echo "Script selesai."